spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        enabled: true
        lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://${KEYCLOAK_SERVER}:8084/realms/mscreditorealm

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-user:12345678@${EUREKA_SERVER}:8761/eureka