spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        enabled: true
        lower-case-service-id: true

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka